### ISSUE TITLE
Support on expo

### ISSUE THREAD

**Issue by shunkakinoki** [ReyRod/reactNativeVideoCall#3]
Hi thanks for the awesome repo!

I'm currently looking into solutions for multi platform mobile development 

Is this repository supported with expo?

**Comment by tycali17** [comment]
Hello,
Expo is not possible to work with when dealing with Twilio (especially their APIs), or just video chat in general. This has been a common issue for years, but Expo remains workable only for less-complex apps. 

Try to create your react-native app without Expo and you should be able to find a solution.
